### ISSUE TITLE
TypeError on parsing cookies

### ISSUE THREAD

**Issue by YerkoPalma** [matthewmueller/x-ray#234] opened 2016-11-08 15:33 UTC
### Subject of the issue

`x-ray` is failling when parsing cookies

### Your environment

* version of node: *v4.6.1*
* version of npm: *v2.15.9*

### Steps to reproduce

I run this code

```javascript
'use strict'
const xray = require('x-ray')()
const URL = 'http://www.senado.cl/appsenado/index.php?mo=senadores&ac=listado'

function senado (options) {
  options = options || {}
  xray(URL, {
    title: 'title'
  })(console.log)
}
senado()
module.exports = senado
```

### Expected behaviour

It should have logged 

```bash
$ Senado República de Chile - Lista Senadores
```

### Actual behaviour

It throws

```
/home/ubuntu/workspace/node_modules/x-ray/node_modules/x-ray-crawler/node_modules/superagent/node_modules/cookiejar/cookiejar.js:71
                key = pair[1],
                          ^

TypeError: Cannot read property '1' of null
    at Cookie.parse (/home/ubuntu/workspace/node_modules/x-ray/node_modules/x-ray-crawler/node_modules/superagent/node_modules/cookiejar/cookiejar.js:71:27)
    at new Cookie (/home/ubuntu/workspace/node_modules/x-ray/node_modules/x-ray-crawler/node_modules/superagent/node_modules/cookiejar/cookiejar.js:32:22)
    at /home/ubuntu/workspace/node_modules/x-ray/node_modules/x-ray-crawler/node_modules/superagent/node_modules/cookiejar/cookiejar.js:251:20
    at Array.map (native)
    at CookieJar.setCookies (/home/ubuntu/workspace/node_modules/x-ray/node_modules/x-ray-crawler/node_modules/superagent/node_modules/cookiejar/cookiejar.js:250:27)
    at Agent.saveCookies (/home/ubuntu/workspace/node_modules/x-ray/node_modules/x-ray-crawler/node_modules/superagent/lib/node/agent.js:40:25)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/node_modules/x-ray/node_modules/x-ray-crawler/node_modules/superagent/lib/node/index.js:921:12)
    at emitNone (events.js:72:20)
```

**Comment by arajeev** [comment] 2018-03-08 01:10
@YerkoPalma I'm also facing this issue. Were you able to find a fix to this error?

**Comment by bfelbo** [comment] 2018-03-15 22:38
Same here. Any suggestions for how to potentially fix it?

**Comment by danielmcq** [comment] 2018-04-19 02:38
I have put in a PR to help avoid this issue (https://github.com/bmeck/node-cookiejar/pull/34). There are a couple of obstacles which prevent my PR from solving your problem. First, I'm not a maintainer of the https://github.com/bmeck/node-cookiejar project, so I must wait for my fix to get approved and merged. Second, there are still the https://github.com/visionmedia/superagent and https://github.com/matthewmueller/x-ray projects which will need to be updated after to include the fixed version of https://github.com/bmeck/node-cookiejar.

The root cause of this issue is the site in the example (http://www.senado.cl/appsenado/index.php?mo=senadores&ac=listado) is sending back invalid cookies. There are no values in the cookie, just cookie metadata. Below are the headers returned. Notice how the *Set-Cookie* header has no value, only the *HttpOnly* and *Secure* flags. __*It might be faster to contact the webmaster of the site and tell them that their code is sending invalid cookies.*__ You can read more about the standards for cookies here: https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Set-Cookie#Directives.

```
Date: Thu, 19 Apr 2018 02:27:38 GMT
Server: Apache/2.2.23 (Unix)
Access-Control-Allow-Origin: *
Set-Cookie: HttpOnly;Secure
Content-Type: text/html; charset=utf-8
X-Cache: MISS from www.senado.cl
X-Cache-Lookup: HIT from www.senado.cl:80
Via: 1.1 www.senado.cl (squid/3.5.27)
Connection: keep-alive
```

**Closed** 2019-03-27 15:45 UTC
