### ISSUE TITLE
Option to return null when empty

### ISSUE THREAD

**Issue by Panthro** [matthewmueller/x-ray#198] opened 2016-07-13 11:26 UTC
### Subject of the issue

Add an option to return null when empty for schema strict applications
### Expected behaviour

When an element return empty, add the element as a null

Eg:

``` json
{
  "id":"0",
  "name":null
}
```

**Comment by oskarjakiela** [comment] 2016-08-29 12:27
You can use filters as a workaround

```javascript
var Xray = require('x-ray');
var x = Xray({
  filters: {
    nullify: function(value) { return value ? value : null; }
  }
});

x('https://google.com', {
  empty: 'empty | nullify'
});
```

**Comment by simonseddon** [comment] 2017-02-12 10:39
Having the same issue myself and tried a filter with no joy. Tried yours out of interest. No such luck. Have you tried this yourself with any luck?

**Comment by lathropd** [comment] 2019-04-18 03:38
Dupe of #202. Merging.

**Closed by lathropd** 2019-04-18 03:38 UTC
