### ISSUE TITLE
Add set "charset" for webpage.

### ISSUE THREAD

**Issue by simvolice** [matthewmueller/x-ray#268] opened 2017-07-31 12:09 UTC
### Subject of the issue

Describe your issue here.

### Your environment

* version of node: *run node --version*
* version of npm: *run npm --version*

### Steps to reproduce

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

**Comment by m-emelchenkov** [comment] 2017-09-19 08:26
https://github.com/matthewmueller/x-ray/issues/183

**Comment by lathropd** [comment] 2019-03-27 15:26
Closing as duplicate of #183

**Closed by lathropd** 2019-03-27 15:26 UTC
